### ISSUE TITLE
Mod broke with 18.22

### ISSUE THREAD

**Issue by TheSchemm** [Suprcheese/Orbital-Ion-Cannon#38] opened 2020-04-30 23:59 UTC
Now the game won't load unless the mod is disabled

In the change log for 18.22 they stated
> Removed migration for CustomInputPrototype consuming types that were removed in 0.15.24.

![factorio_ion_cannon_error](https://user-images.githubusercontent.com/119007/80770030-a742c880-8b14-11ea-82e8-9d5341cf8f5e.PNG)

**Comment by Suprcheese** [comment] 2020-05-01 06:24
Yes, I think I know what the problem is. I'll try to get an update out shortly.

**Comment by Suprcheese** [comment] 2020-05-01 18:55
Fixed in version 1.8.2. Thank you for your report!

**Closed as completed by Suprcheese** 2020-05-01 18:55 UTC
